# Generated by Django 2.0.5 on 2018-07-27 06:42

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.user_media_cover_path),
        ),
    ]
