# Generated by Django 2.0.5 on 2018-07-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
