# Generated by Django 2.0.5 on 2018-07-31 03:13

import books.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=books.utils.book_media_cover_path),
        ),
    ]
