# Generated by Django 2.0.5 on 2018-11-07 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='read',
            options={'verbose_name_plural': 'Reads (logs)'},
        ),
    ]
